name: Build and push Docker image

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  CURRENT_VERSION: 1.0.1
  BUILD_NUMBER: 0
  IMAGE_NAME: nickdlk/lyprobe

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.CURRENT_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./Readme.md
